### ISSUE TITLE
不刷特

### ISSUE THREAD

**Issue by apples1949** [Caibiii/AnneServer#3]
L 04/28/2022 - 14:55:56: SourceMod error session started
L 04/28/2022 - 14:55:56: Info (map "c2m1_highway") (file "/root/anne/left4dead2/addons/sourcemod/logs/errors_20220428.log")
L 04/28/2022 - 14:55:56: [SM] Exception reported: Failed to create native "LGO_IsMatchModeLoaded", name is probably already in use
L 04/28/2022 - 14:55:56: [SM] Blaming: AnneHappy.smx
L 04/28/2022 - 14:55:56: [SM] Call stack trace:
L 04/28/2022 - 14:55:56: [SM]   [0] CreateNative
L 04/28/2022 - 14:55:56: [SM]   [1] Line 61, modules/ReqMatch.sp::RM_APL
L 04/28/2022 - 14:55:56: [SM]   [2] Line 68, D:\Users\Hasee\Documents\Tencent Files\571720780\FileRecv\MobileFile\1.10ƽ̨\confoglcompmod.sp::AskPluginLoad2
L 04/28/2022 - 14:55:56: [SM] Failed to load plugin "AnneHappy.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by apples1949** [comment]
emmm
启动了rpg,smx就刷特了

**Comment by Caibiii** [comment]
网页下载的插件可能有延迟没更新，可以下打包好的插件包或者git同步，zonemod整合包需要加载一个cfg目录下的AnneHappy.cfg，以及一些插件加载的顺序需要调整，完整包已测试过是没有问题的
