### ISSUE TITLE
AnneHappy.smx插件出现报错，无法加载

### ISSUE THREAD

**Issue by honghl5** [Caibiii/AnneServer#4]
我的错误日志里出现这样的报错，找不到是何原因

L 05/05/2022 - 06:04:13: [SM] Exception reported: Failed to create native "LGO_IsMatchModeLoaded", name is probably already in use
L 05/05/2022 - 06:04:13: [SM] Blaming: AnneHappy.smx
L 05/05/2022 - 06:04:13: [SM] Call stack trace:
L 05/05/2022 - 06:04:13: [SM]   [0] CreateNative
L 05/05/2022 - 06:04:13: [SM]   [1] Line 61, modules/ReqMatch.sp::RM_APL
L 05/05/2022 - 06:04:13: [SM]   [2] Line 68, D:\Users\Hasee\Documents\Tencent Files\571720780\FileRecv\MobileFile\1.10平台\confoglcompmod.sp::AskPluginLoad2
L 05/05/2022 - 06:04:13: [SM] Failed to load plugin "AnneHappy.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by Caibiii** [comment]
整合zonemod后的固定报错，不会影响使用，实际是加载的

**Comment by Caibiii** [comment]
confoglcompmod.smx 与 AnneHappy.smx共存同目录会产生这一个错误日志，因为只是个小问题不会影响使用所以不打算解决了

**Comment by honghl5** [comment]
好的，谢谢~
